---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(dplyr)
```

```{r}
energia_pLDDT_RSA <- read_csv("C:/tablas_tesina/1er capitulo/energia_pLDDT_RSA.csv")
```


```{r}
Analisis_mut_snp <- read_csv("C:/tablas_tesina/1er capitulo/Analisis_SNP")
```

```{r}
Analisis_mut_SNP<-cbind(Analisis_mut_snp,mutaciones$Protein_position)
```


```{r}
names(Analisis_mut_SNP)[names(Analisis_mut_SNP) == "mutaciones$Protein_position"] <- "pos_mut"
view(Analisis_mut_SNP)
```




```{r}
kk <- merge(energia_pLDDT_RSA, Analisis_mut_SNP, by.x = c("Uniprot_ID", "Posicion_mut"), by.y = c("Entry", "pos_mut"))
```
#esto se necesita hacer poirque se duplican algunos datos

```{r}
indices_a_eliminar <- c(258,540,542,559,561,631,633)
kkck <- kk[-indices_a_eliminar, ]
```

```{r}
view(kkck)
write.csv(kkck,"C:/tablas_tesina/1er capitulo/SNPs_patogenicidad.csv")
```


```{r}
kungfu<- read_csv("C:/tablas_tesina/kung_funding_data_20_5_23.csv")
```

```{r}
kungfu_amy<-subset(kungfu,category_amyloids=="Amyloid")
```

```{r}
amy_nean<-merge(kungfu_amy,kkck,by.x="uniprot_id",by.y="Uniprot_ID")
view(amy_nean)
```



















































































